### PR TITLE
Create emperorjoker.yml

### PR DESCRIPTION
**Pull request by superiorxman**

### CODE REVIEW

**Comment by superiorxman** [comment]
http://static.comicvine.com/uploads/original/3/33046/934345-emperorjokerpage17smart.jpg

Joker gains 99.9% of Mr.Myx's powers

**Comment by superiorxman** [comment]
http://static.comicvine.com/uploads/original/3/39119/932948-mxyjokerskillej8.jpg

for /destroyworld

**Comment by superiorxman** [comment]
http://pm1.narvii.com/5771/a8b77b8e30e134e709ed45a93144379dbacba81a_hq.jpg

superman fly's through joker's head and he still lives
kill.immune

**Comment by superiorxman** [comment]
takes control of the consciousness of some of the most powerful beings in the DC universe
https://qph.ec.quoracdn.net/main-qimg-22da31eab1ad7c9173c4230745cb5e4a
  /mindcontrol

**Comment by superiorxman** [comment]
https://static.comicvine.com/uploads/original/12/128157/2700395-emperorjokerpage13.jpg
/grow
there's a better panel of him giant but i couldn't find it

**Comment by malonnnn** [comment]
You need to edit emperor joker, not create a new one, we already have emperor joker

**Pull request closed without merging**
