### PR TITLE
Create krypto.yml

### PR DESCRIPTION
**Pull request by MH03**
Proof for everything https://www.dccomics.com/characters/krypto

### CODE REVIEW

**Comment by MH03** [comment]
https://comicvine.gamespot.com/krypto/4005-8332/ also proof

**Comment by malonnnn** [comment]
You need to read http://omnivs.hopto.org/howtomakeahero.html

Q: What kinds of powers are accepted?
A: Any power that has ACTUALLY been shown in a movie, TV show, comic, or other official merchandise.
Examples: Barry Allen can turn invisible because he can move so fast. This does not mean that every hero can turn invisible because they move fast. The character MUST ACTUALLY have been shown to use it. Also, talking about it does not count. If Savitar says "I can turn invisible because I move fast" but he never actually turns invisible, then it does not count. ONLY PICS OR VIDEOS COUNT AS PROOF, NO WIKIS OR FANSITES

**Comment by MH03** [comment]
ok sorry

**Comment by MH03** [comment]
https://static.comicvine.com/uploads/original/1/15293/329773-115483-krypto.jpg for flight and laservision

**Comment by MH03** [comment]
https://static.comicvine.com/uploads/original/0/9167/245319-158641-krypto.jpg for strength

**Comment by MH03** [comment]
https://static.comicvine.com/uploads/original/0/9167/245375-110642-krypto.jpg for resistance

**Pull request merged**
