### PR TITLE
CONTENT DELETED FOREVER

### PR DESCRIPTION
**Pull request by Gemo599**
Here we go again!

### CODE REVIEW

**Comment by Gemo599** [comment]
Chara the first human
Real Knife - ATK: 999999
From UNDERTALE
Genocide End: "Since you were in the control?"

**Comment by malonnnn** [comment]
i see no picture or video

**Comment by Gemo599** [comment]
https://www.youtube.com/watch?v=-zIrwCnYzls
https://www.youtube.com/watch?v=P-b9vSFh8-g

**Comment by Gemo599** [comment]
link 1: 0:13
link 2: http://undertale.wikia.com/wiki/Real_Knife (new link)

**Comment by Gemo599** [comment]
link 2: 00:8
ATK: 9999

**Comment by Gemo599** [comment]
I hope you'll all die.

**Comment by Gemo599** [comment]
I HOPE YOU WILL ALL DIE IN HELLFIRE

**Pull request closed without merging**
