### PR TITLE
Create jason.yml

### PR DESCRIPTION
**Pull request by superiorxman**
can you make him mute like BlackBolt? I couldn't figure out how to do it myself

### CODE REVIEW

**Comment by superiorxman** [comment]
http://img.actucine.com/wp-content/uploads/2015/02/Jason-Voorhees.jpg
Machete

**Comment by superiorxman** [comment]
https://gbhbl.files.wordpress.com/2015/10/friday-the-13th-8-boxing-gif.gif?resize=500%2C261
strength 
you can tone down the strength if you want

**Comment by superiorxman** [comment]
https://www.youtube.com/watch?v=JnPmfP_HOHw
all deaths and resurrections
anything after 2:13

**Comment by superiorxman** [comment]
just in case the previous proof wasn't good enough

**Comment by superiorxman** [comment]
https://media.giphy.com/media/6qaQElfOgbQY/giphy.gif
water breathing, that ugly kid coming out of the water is jason

**Comment by superiorxman** [comment]
The proof was harder to get than i expected, theres not a lot of available video evidence of his abilities

**Comment by malonnnn** [comment]
Look in black bolts file, that's how you make him mute

**Pull request merged**
